# Generated by Django 3.2.6 on 2021-09-02 17:08

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Название')),
                ('template_of_contract', models.FileField(upload_to='upload/', validators=[main.models.check_format_of_file], verbose_name='Шаблон договора')),
                ('amount', models.PositiveIntegerField(null=True, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('Актуально', 'Actual'), ('Устарело', 'Outdated')], default='Актуально', max_length=50, verbose_name='Статус')),
                ('type', models.CharField(choices=[('Основной', 'Basic'), ('Продление', 'Renewal')], max_length=50, verbose_name='Тип')),
                ('company', models.CharField(choices=[('ООО "Комьюнити Менеджмент Солюшнз"', 'Cms'), ('ООО "ДЕЛОВОЙ КЛУБ"', 'Dc')], max_length=50, verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
            },
        ),
    ]
