# Generated by Django 3.2.6 on 2021-08-30 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Url')),
                ('template_of_contract', models.FileField(upload_to='upload/', verbose_name='Шаблон договора')),
                ('amount', models.PositiveIntegerField(null=True, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('Актуально', 'Actual'), ('Устарело', 'Outdated')], default='Актуально', max_length=50, verbose_name='Статус')),
                ('type', models.CharField(choices=[('Основной', 'Basic'), ('Продление', 'Renewal')], max_length=50, verbose_name='Тип')),
                ('company', models.CharField(choices=[('ООО "Комьюнити Менеджмент Солюшнз"', 'Cms'), ('ООО "ДЕЛОВОЙ КЛУБ"', 'Dc')], max_length=50, verbose_name='Компания')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.branch')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
            },
        ),
    ]
