# Generated by Django 3.2.6 on 2021-09-03 10:10

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracttemplate',
            options={'verbose_name': 'Шаблон контракта', 'verbose_name_plural': 'Шаблоны контрактов'},
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField(default='24546799', verbose_name='Номер договора')),
                ('payment', models.FileField(null=True, upload_to='payment/', validators=[main.models.check_format_of_payment], verbose_name='Счет на оплату')),
                ('signed_contract', models.FileField(null=True, upload_to='signed_contract/', validators=[main.models.check_format_signed_contract], verbose_name='Подписанный договор')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Дата генерации')),
                ('date_signed', models.DateField(blank=True, null=True, verbose_name='Дата подписания')),
                ('status', models.CharField(choices=[('Направлен', 'Directed'), ('Подписан', 'Signed'), ('Отменен', 'Canceled'), ('Отказ', 'Refusal')], default='Направлен', max_length=50, verbose_name='Статус')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('amount', models.PositiveIntegerField(null=True, verbose_name='Сумма')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('contract_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contracttemplate')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
            },
        ),
    ]
