# Generated by Django 3.2.6 on 2021-09-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-id'], 'verbose_name': 'Контракт', 'verbose_name_plural': 'Контракты'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='slug',
            field=models.SlugField(default=24546799, unique=True, verbose_name='Url'),
        ),
    ]
