# Generated by Django 3.2.6 on 2022-04-04 18:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 4, 4, 18, 4, 14, 842958, tzinfo=utc), verbose_name='Дата генерации'),
        ),
    ]
