# Generated by Django 3.2.6 on 2022-04-15 14:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationcode',
            name='date_generated_code',
            field=models.CharField(default=1650033823.2180426, max_length=200, verbose_name='Секунды генерации кода'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 4, 15, 14, 43, 43, 218042, tzinfo=utc), verbose_name='Дата генерации'),
        ),
    ]
