# Generated by Django 3.2.6 on 2022-04-04 17:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 4, 4, 17, 37, 9, 464416, tzinfo=utc), verbose_name='Дата генерации'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='num_passport',
            field=models.IntegerField(blank=True, max_length=6, null=True, verbose_name='Номер паспорт'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='series_passport',
            field=models.IntegerField(blank=True, max_length=4, null=True, verbose_name='Серия паспорт'),
        ),
    ]
