# Generated by Django 3.2.6 on 2021-08-30 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contract_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='branch',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.branch'),
        ),
    ]
