# Generated by Django 3.2.6 on 2021-09-07 15:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210903_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 9, 7, 15, 50, 13, 285823, tzinfo=utc), verbose_name='Дата генерации'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.PositiveBigIntegerField(default=24546799, verbose_name='Номер договора'),
        ),
    ]
