# Generated by Django 3.2.6 on 2022-03-25 16:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contract_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='passport',
        ),
        migrations.AddField(
            model_name='contract',
            name='num_passport',
            field=models.CharField(blank=True, default='Данных нет', max_length=6, null=True, verbose_name='Номер паспорт'),
        ),
        migrations.AddField(
            model_name='contract',
            name='series_passport',
            field=models.CharField(blank=True, default='Данных нет', max_length=4, null=True, verbose_name='Серия паспорт'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 3, 25, 16, 35, 48, 704545, tzinfo=utc), verbose_name='Дата генерации'),
        ),
    ]
