# Generated by Django 3.2.6 on 2021-08-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_contract_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название'),
        ),
    ]
