# Generated by Django 3.2.6 on 2021-11-21 13:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211121_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.PositiveIntegerField(max_length=300, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 11, 21, 13, 18, 31, 360071, tzinfo=utc), verbose_name='Дата генерации'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='full_name',
            field=models.CharField(max_length=300, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='passport',
            field=models.CharField(blank=True, default='Данных нет', max_length=20, null=True, verbose_name='Паспорт'),
        ),
    ]
