# Generated by Django 3.2.6 on 2021-09-07 18:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210907_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 9, 7, 18, 1, 10, 964256, tzinfo=utc), verbose_name='Дата генерации'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signed_contract',
            field=models.FileField(null=True, upload_to='signed_contract/', verbose_name='Подписанный договор'),
        ),
    ]
