# Generated by Django 3.2.6 on 2021-08-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contract_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Url'),
        ),
    ]
