# Generated by Django 3.2.6 on 2021-09-13 10:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210907_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 9, 13, 10, 57, 2, 4028, tzinfo=utc), verbose_name='Дата генерации'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment',
            field=models.FileField(blank=True, null=True, upload_to='payment/', validators=[main.models.check_format_of_payment], verbose_name='Счет на оплату'),
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='company',
            field=models.CharField(choices=[('КМС', 'ООО "Комьюнити Менеджмент Солюшнз"'), ('ДК', 'ООО "ДЕЛОВОЙ КЛУБ"')], max_length=50, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='status',
            field=models.CharField(choices=[('Актуально', 'Actual'), ('Устарело', 'Outdated')], default='Актуально', max_length=100, verbose_name='Статус'),
        ),
    ]
