# Generated by Django 3.2.6 on 2021-09-13 16:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210913_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 9, 13, 16, 29, 19, 489971, tzinfo=utc), verbose_name='Дата генерации'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('Направлен', 'Направлен'), ('Подписан', 'Подписан'), ('Отменен', 'Отменен'), ('Отказ', 'Отказ')], default='Направлен', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='status',
            field=models.CharField(choices=[('Актуально', 'Актуально'), ('Устарело', 'Устарело')], default='Актуально', max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='type',
            field=models.CharField(choices=[('Основной', 'Основной'), ('Продление', 'Продление')], max_length=50, verbose_name='Тип'),
        ),
    ]
