# Generated by Django 3.2.6 on 2021-08-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_contract_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='branch',
        ),
    ]
