# Generated by Django 3.2.6 on 2021-08-31 09:57

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_contract_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='template_of_contract',
            field=models.FileField(upload_to='upload/', validators=[main.models.check_format_of_file], verbose_name='Шаблон договора'),
        ),
    ]
