# Generated by Django 3.2.6 on 2021-09-14 17:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210914_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 9, 14, 17, 53, 19, 566805, tzinfo=utc), verbose_name='Дата генерации'),
        ),
    ]
