# Generated by Django 3.2.6 on 2021-10-05 14:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_contract_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='contract',
            name='passport',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Паспорт'),
        ),
        migrations.AddField(
            model_name='contract',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 10, 5, 14, 39, 50, 692852, tzinfo=utc), verbose_name='Дата генерации'),
        ),
    ]
