# Generated by Django 3.2.6 on 2021-10-05 14:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211005_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='identifier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Индетификатор'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 10, 5, 14, 41, 55, 661998, tzinfo=utc), verbose_name='Дата генерации'),
        ),
    ]
