# Generated by Django 3.2.6 on 2021-10-06 08:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_contract_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 8, 13, 2, 387539, tzinfo=utc), verbose_name='Дата генерации'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='email',
            field=models.EmailField(blank=True, default='Данных нет', max_length=50, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='identifier',
            field=models.CharField(blank=True, default='Данных нет', max_length=50, null=True, verbose_name='Индетификатор'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='passport',
            field=models.CharField(blank=True, default='Данных нет', max_length=9, null=True, verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='phone',
            field=models.CharField(blank=True, default='Данных нет', max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
