# Generated by Django 3.2.6 on 2021-10-23 21:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_contract_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 10, 23, 21, 11, 2, 173185, tzinfo=utc), verbose_name='Дата генерации'),
        ),
    ]
