# Generated by Django 3.2.6 on 2021-10-25 10:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20211024_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationcode',
            name='code',
            field=models.PositiveIntegerField(max_length=5, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='authenticationcode',
            name='generated_code',
            field=models.DateField(default=datetime.datetime(2021, 10, 25, 10, 58, 56, 948241, tzinfo=utc), verbose_name='Дата генерации кода'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 10, 25, 10, 58, 56, 947241, tzinfo=utc), verbose_name='Дата генерации'),
        ),
    ]
