# Generated by Django 3.2.6 on 2021-10-29 18:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20211025_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationcode',
            name='date_generated_code',
            field=models.DateField(default=datetime.datetime(2021, 10, 29, 18, 44, 41, 445031, tzinfo=utc), verbose_name='Дата генерации кода'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 10, 29, 18, 44, 41, 444031, tzinfo=utc), verbose_name='Дата генерации'),
        ),
    ]
