# Generated by Django 3.2.6 on 2021-11-01 16:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20211029_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationcode',
            name='date_generated_code',
            field=models.DateField(auto_now_add=True, verbose_name='Дата генерации кода'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 11, 1, 16, 37, 33, 447804, tzinfo=utc), verbose_name='Дата генерации'),
        ),
    ]
