# Generated by Django 3.2.6 on 2021-11-09 17:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20211101_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 11, 9, 17, 23, 22, 598920, tzinfo=utc), verbose_name='Дата генерации'),
        ),
    ]
